### ISSUE TITLE
[Bug]: Trashing doesn't keep paths of files in *Linux*

### ISSUE THREAD

**Issue by stevenxxiu** [chrisgrieser/nvim-genghis#37]
### Bug Description

Trashing on Linux is meant to keep file paths in `~/.local/share/Trash/info/`. See [solus - How does the trash directory work? - Unix & Linux Stack Exchange](https://unix.stackexchange.com/a/672544). There might be more requirements I haven't read about.

Other plugins say <https://github.com/nvim-tree/nvim-tree.lua/blob/50f30bcd8c62ac4a83d133d738f268279f2c2ce2/doc/nvim-tree-lua.txt#L1405> use another utility to do this properly.

What are your thoughts on using an external utility instead to handle this properly?

### neovim version

```Text
v0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
I never used Linux, and I am therefore really familiar with it. Thus, I would kind of prefer for someone who actually uses Linux to fix this via PR, to be honest. The code for trashing a file is here:
https://github.com/chrisgrieser/nvim-genghis/blob/8349eb8843e1399a6cb9ef92ea97d980cfa0ee01/lua/genghis.lua#L260-L298

Generally, I'd like to avoid having dependencies, since this plugin is intended to be lightweight, but then again, I am not familiar with how common certain CLIs are on Linux.

**Comment by stevenxxiu** [comment]
Thanks for the comment. I'm a *Linux* user myself.

It makes sense to have minimal dependencies. But I think to use trash at all, requires some software. It's not as simple as just moving a file to some directory.

*nvim-tree* uses the `gio` binary, which is a part of `glib2`, which is then required by `gtk3`, `gtk4`. So if you're using any GUI software, chances are you have it installed.

On the terminal I'm using <https://github.com/andreafrancia/trash-cli>.

It would be possible to write implement this, but given the above and chances of introducing bugs I'm personally not inclined to do this. I think the line at <https://github.com/chrisgrieser/nvim-genghis/blob/8349eb8843e1399a6cb9ef92ea97d980cfa0ee01/lua/genghis.lua#L292> is buggy. It adds a suffix `~` if the file exists in trash, but what if a file like that already exists from a previous trash operation?

**Comment by stevenxxiu** [comment]
Oh btw thanks for exposing the API. An external tool, say `trash-put`, can be used like:

```lua
{ '<leader>ot', function()
  local path = vim.fn.expand('%:p')

  local err_msg = ''

  vim.fn.jobstart('trash-put "' .. path .. '"', {
    detach = true,
    on_stderr = function (_, data)
      err_msg = err_msg .. (data and table.concat(data, ' '))
    end,
    on_exit = function(_, rc)
      local utils = require('genghis.utils')

      if rc == 0 then
        utils.bwipeout()
        utils.notify(('%q deleted'):format(path))
      else
        utils.notify(('trash of %q failed: ' .. err_msg):format(path), 'warn')
      end
    end
  })
end },
```

**Comment by chrisgrieser** [comment]
yeah, I figured a proper module structure would help with contributions (since the plugin's code grew to 400+ lines already, that was overdue anyway…)

Since I do not have a Linux machine, why don't you just create a fork and test a while whether it works on your end? If there are no issues with it then you can create a PR to merge it

**Comment by stevenxxiu** [comment]
I can do that, but what about *Mac*? Would you still want your original code there?

**Comment by chrisgrieser** [comment]
just do Linux. Simply moving to the correct trash directory works fine on mac for me
